environment:
    global:
        VERBOSE_SUBPROCESS: 1
    matrix:
        - PYTHON: "C:/Python36"
        - PYTHON: "C:/Python36-x64"
init:
    - "set PATH=%PYTHON%/scripts;%PYTHON%;%PATH%"
    - "python --version"
    - "pip --version"
install:
    - "pip install --disable-pip-version-check --user --upgrade setuptools pip"
    - "pip install -r requirements-dev.txt"
    - "pip list --format columns"
    - "choco install shellcheck"
    - "shellcheck --version"
build_script:
    - "inv check"
test_script:
    - "inv test"
